name: Manter Supabase Ativo

on:
  schedule:
    # Roda todos os dias às 05:00 da manhã (horário UTC)
    - cron: '0 5 * * *'
  workflow_dispatch: # Permite que você teste clicando em um botão

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Enviando sinal de atividade para o Supabase
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
